#include "stdafx.h"
#include "LEVEL_CHARACTERSELECT.H"
#include "LEVEL_CHARACTERSELECT.H"
#include "LEVEL_CHARACTERSELECT.H"
#include "LEVEL_CHARACTERSELECT.H"
#include "LEVEL_CHARACTERSELECT.H"

HRESULT CLevel_CharacterSelect::Initialize()
{
    return E_NOTIMPL;
}

void CLevel_CharacterSelect::Tick(_float fTimeDelta)
{
}

HRESULT CLevel_CharacterSelect::Render()
{
    return E_NOTIMPL;
}

CLevel_CharacterSelect* CLevel_CharacterSelect::Create()
{
    return nullptr;
}

void CLevel_CharacterSelect::Free()
{
}
